
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SaiGaiYuShi
    username: root
    password: 6PTXGtQ5jU7B#mbxEUd
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8813
mybatis:
  mapper-locations: classpath:xml/*.xml
